'use client'

import { Check, Clipboard, Download, LoaderCircle, Sparkles } from 'lucide-react'
import { useState } from 'react'

export function Panel({ title, meta, children, className = '' }) { return <section className={`surface-glow overflow-hidden rounded-xl border border-border bg-card/70 ${className}`}><div className="flex items-center justify-between border-b border-border/70 bg-secondary/20 px-4 py-3"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary shadow-[0_0_10px_currentColor]" /><h2 className="font-mono text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">{title}</h2></div>{meta && <span className="font-mono text-[11px] text-muted-foreground">{meta}</span>}</div>{children}</section> }

export function ActionButton({ children, onClick, disabled, variant = 'primary', type = 'button' }) { return <button type={type} disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold transition-all disabled:cursor-not-allowed disabled:opacity-50 ${variant === 'primary' ? 'bg-primary text-primary-foreground shadow-[0_0_18px_rgba(103,232,208,0.14)] hover:brightness-110' : 'border border-border bg-secondary/60 text-foreground hover:border-primary/30 hover:bg-secondary'}`}>{disabled && <LoaderCircle className="size-3.5 animate-spin" />}{children}</button> }

export function CodeOutput({ value, language = 'json', empty = 'Your generated output will appear here.' }) { const [copied, setCopied] = useState(false); const copy = async () => { if (!value) return; await navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1400) }; const download = () => { const blob = new Blob([value], { type: language === 'sql' ? 'text/plain' : 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `devtoolkit-output.${language === 'sql' ? 'sql' : 'json'}`; a.click(); URL.revokeObjectURL(url) }; return <div className="relative min-h-64 bg-[#0c1113] p-5"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[11px] text-muted-foreground">output.{language}</span><div className="flex gap-2"><ActionButton variant="ghost" onClick={copy} disabled={!value}>{copied ? <><Check className="size-3.5" /> Copied</> : <><Clipboard className="size-3.5" /> Copy</>}</ActionButton><ActionButton variant="ghost" onClick={download} disabled={!value}><Download className="size-3.5" /> Save</ActionButton></div></div><pre className="max-h-[30rem] overflow-auto whitespace-pre-wrap font-mono text-[13px] leading-6 text-cyan-100">{value || <span className="text-muted-foreground">{empty}</span>}</pre></div> }

export function ErrorBanner({ message }) { if (!message) return null; return <div role="alert" className="mb-5 rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{message}</div> }

export function GenerateLabel() { return <span className="inline-flex items-center gap-2"><Sparkles className="size-3.5" /> Generate</span> }
